### ISSUE TITLE
399 linux version: list index out of range

### ISSUE THREAD

**Issue by GoogleCodeExporter** [djsmisc/pinguino32#17]
```
./pinguino_start.sh 

Traceback (most recent call last):
  File "./pinguino.py", line 5, in <module>
    from wxgui.pinguino import getOptions, Pinguino, setGui
  File "/home/pic32/pinguinoX.3rev399/wxgui/__init__.py", line 4, in <module>
    import check
  File "/home/pic32/pinguinoX.3rev399/wxgui/check.py", line 222, in <module>
    from editor import functionsHelp
  File "/home/pic32/pinguinoX.3rev399/wxgui/editor/__init__.py", line 10, in <module>
    from general import General
  File "/home/pic32/pinguinoX.3rev399/wxgui/editor/general.py", line 29, in <module>
    from dic import Snippet, Autocompleter
  File "/home/pic32/pinguinoX.3rev399/wxgui/editor/dic.py", line 33, in <module>
    if os.name == "posix": date = "/".join([t[3], t[1], t[5]])
IndexError: list index out of range

```

Original issue reported on code.google.com by `pijo...@gmail.com` on 14 May 2012 at 10:01

**Comment by GoogleCodeExporter** [comment]
```
solved in revision 404. The problem was in wxgui/editor/dic.py
http://code.google.com/p/pinguino32/source/diff?spec=svn404&r=404&format=side&pa
th=/branches/x.3/wxgui/editor/dic.py
```

Original comment by `jp.mandon@gmail.com` on 16 May 2012 at 5:47
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `rblanchot@gmail.com` on 23 Apr 2013 at 8:13
- Changed state: **Fixed**
