### ISSUE TITLE
Problem starting the IDE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [djsmisc/pinguino32#34]
```
What steps will reproduce the problem?
1. Download and uncompress the ide for linux 64
2. Execute the  ./pinguino_lin64.sh 


------------------------------------------
What is the expected output? What do you see instead?
I expect the program to open a window. I get:
Traceback (most recent call last):
  File "./pinguino.py", line 5, in <module>
    from wxgui.pinguino import getOptions, Pinguino, setGui
  File "/tmp/pinguinoX.3rev399/wxgui/__init__.py", line 4, in <module>
    import check
  File "/tmp/pinguinoX.3rev399/wxgui/check.py", line 222, in <module>
    from editor import functionsHelp
  File "/tmp/pinguinoX.3rev399/wxgui/editor/__init__.py", line 10, in <module>
    from general import General
  File "/tmp/pinguinoX.3rev399/wxgui/editor/general.py", line 29, in <module>
    from dic import Snippet, Autocompleter
  File "/tmp/pinguinoX.3rev399/wxgui/editor/dic.py", line 33, in <module>
    if os.name == "posix": date = "/".join([t[3], t[1], t[5]])
IndexError: list index out of range

and the log says:
xandacona@xanda-desktop:/tmp/pinguinoX.3rev399$ cat pinguino.log Pinguino 
started at Mon Dec 17 09:12:15 2012

Python version is OK (>=2.5)
System host is GNU/Linux
8-bit compiler OK.
32-bit compiler OK.
wx.python successfully loaded
wx.aui successfully loaded
Regex successfully loaded
Shutil successfully loaded
Subprocess successfully loaded
GetText successfully loaded
Locale successfully loaded
WebBrowser successfully loaded
USB successfully loaded
Serial successfully loaded
Threading successfully loaded
Frames successfully loaded

------------------------------------------
What version of the product are you using? On what operating system?
pinguinoX.3rev399.tar.lzma
Linux 2.6.35-32-generic #67-Ubuntu SMP Mon Mar 5 19:39:49 UTC 2012 x86_64 
GNU/Linux
Ubuntu 10.10

------------------------------------------
Please provide any additional information below.

```

Original issue reported on code.google.com by `xandac...@gmail.com` on 17 Dec 2012 at 8:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `rblanchot@gmail.com` on 23 Apr 2013 at 9:56
- Changed state: **Fixed**
