### ISSUE TITLE
X.4 IDE can't start up with ja locale file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [djsmisc/pinguino32#45]
```
X.4 IDE can't start up with ja locale file.

Pinguino X.4 rev.778
On Windows7(32bit)

Pinguino.log is 'Everything is ok'.

'ja locale file' is attached with 
Pinguino-X4-EasyPack-Win32-Rev685mod-v01-2013-02.7z as locale/ja/*.

pinguniPanic file shows,
Traceback (most recent call last):
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_misc.py", line 1358, in Notify
    self.notify()
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 14771, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "pinguino.py", line 57, in ShowMain
    frame.__initPinguino__(None)
  File "Q:\00pinguino\x4-svn-ide\x.4\wxgui\pinguino.py", line 90, in __initPinguino__
    self.initIDEobjects() 
  File "Q:\00pinguino\x4-svn-ide\x.4\wxgui\editor\__init__.py", line 69, in initIDEobjects
    if self.getElse("Main", "Tools", "True"): self.auiManager.GetPane(self.lat).Hide()
AttributeError: 'Pinguino' object has no attribute 'auiManager'
```

Original issue reported on code.google.com by `inu.ku...@gmail.com` on 25 Apr 2013 at 10:32

**Comment by GoogleCodeExporter** [comment]
```
This issue dose not occur on the latest version.

```

Original comment by `inu.ku...@gmail.com` on 1 May 2013 at 12:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `inu.ku...@gmail.com` on 1 May 2013 at 12:58
- Changed state: **Fixed**
